### ISSUE TITLE
problem API balance

### ISSUE THREAD

**Issue by uchyp** [zulucrypto/mobius-php#2]
![image](https://user-images.githubusercontent.com/12573265/35612921-f2fe11ca-069c-11e8-97dc-f7bc2e13d46f.png)

whats wrong with my code ?
but when i dump appstore variable i think it work

**Comment by zulucrypto** [comment]
@uchyp - Could you include any error messages you're getting?

Also, could you verify that the `$EMAIL` is for a user that has deposited tokens into your app?

**Comment by uchyp** [comment]
solved bro , my bad... incomplete storing my uid.....thanks

**Comment by uchyp** [comment]
just opinion, make the library for framework it's to be good bro
